version: '3.7'
services:
  db:
    container_name: rc_postgres
    image: postgres:13.7
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    expose:
      - "5432"
  minio:
    container_name: rc_minio
    image: minio/minio:latest
    volumes:
      - ../media:/data
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command:
      - server
      - /data
  smtp:
    container_name: rc_mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    expose:
      - "1025"
  nginx:
    container_name: rc_nginx
    image: fholzer/nginx-brotli:v1.18.0
    ports:
      - "8081:443"
    volumes:
      - ../static/:/usr/share/nginx/html/:ro
      - ../nginx/certs:/usr/share/nginx/certs/:ro
      - ../nginx/routechoices.conf:/etc/nginx/conf.d/routechoices.conf:ro
    links:
      - minio
      - django
  django:
    container_name: rc_django
    image: rphlo/routechoices-dev-server
    stop_signal: SIGINT
    volumes:
      - ../:/app/:rw
    environment:
      DJANGO_WATCHMAN_TIMEOUT: 20
    ports:
      - "2000:2000"
      - "2002:2002"
    expose:
      - "2000"
      - "2002"
    links:
      - db
      - minio
      - smtp
    command: ['/venv/bin/python3.10', './manage.py', 'runserver', '0.0.0.0:8000']
